### ISSUE TITLE
API key in .env file

### ISSUE THREAD

**Issue by thedrewery** [thedrewery/fly-by-advisor#2]
@jasonbarry why am I unable to access the API key from my .env file in the App.vue file when I'm making an API call? 🤔

**Comment by jasonbarry** [comment]
is `VUE_APP_API_KEY` in https://github.com/thedrewery/fly-by-advisor/blob/main/src/App.vue#L20 considered secret? If so, you shouldn't include in your clientside code, because it would expose the secret to anyone who inspects your frontend. Instead, you should use it in a lambda / Netlify function, so that your frontend proxies through the serverless function to hit the `airlabs.co` endpoint

**Comment by jasonbarry** [comment]
In Netlify, you'll want to [create an environment variable](https://docs.netlify.com/environment-variables/get-started/#site-environment-variables) on the site that has the key and value, if you haven't already

**Comment by thedrewery** [comment]
@jasonbarry Thanks! Yes, in theory this API key should be a secret and I wanted to find the best way to be able to access it while still keeping it a secret. Netlify functions to the rescue!
